# Generated by Django 5.0.1 on 2024-02-05 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_timestamp_applyjob'),
        ('resume', '0003_alter_resume_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.resume'),
        ),
    ]
