# Generated by Django 5.0.1 on 2024-02-06 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_applyjob_resume'),
        ('resume', '0003_alter_resume_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='resume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.resume'),
        ),
    ]
