# Generated by Django 5.0.1 on 2024-02-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_applyjob_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='resume',
        ),
    ]
