# Generated by Django 5.0.1 on 2024-02-06 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_remove_applyjob_resume'),
        ('resume', '0003_alter_resume_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.resume'),
        ),
    ]
