# Generated by Django 5.0.1 on 2024-02-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_rename_location_job_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
