# Generated by Django 5.0.1 on 2024-02-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_alter_job_industry_alter_job_state_delete_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='industry',
            field=models.CharField(blank=True, choices=[('IT', 'IT'), ('Health', 'Health'), ('Finance', 'Finance')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(blank=True, choices=[('Ndola', 'Ndola'), ('Lusaka', 'Lusaka'), ('Kitwe', 'Kitwe')], max_length=100, null=True),
        ),
    ]
